### ISSUE TITLE
Fatal error: pattern.indexOf is not a function

### ISSUE THREAD

**Issue by emersonhsieh** [mindcandy/pixijs-generator#2]
When I attempt to run `grunt serve:dist` this error always shows up at this step.

> Running "newer:imagemin:files" (newer) task
> Fatal error: pattern.indexOf is not a function

I'm running this command on the default project without any modifications.  Are there any other missing dependencies that can cause this problem or are there modifications needed in Gruntfile.js?

Thanks!

**Comment by Motonstron** [comment]
I've just updated the project to v1.0.3, which includes a newer version of the _imagemin_ dependency. I've also fixed an error with uglifying the project as well. 

I've tested _grunt serve:dist_ on the default/scaffolding project with no errors.

If you are still having errors could you please tell me what version of node you're running, and if you could run the command _grunt serve:dist -d -v_ to get more information, and update the issue.

Thanks

**Comment by emersonhsieh** [comment]
The update worked perfectly.

As a side note, the link in `you can find demo projects using this generator here` at the `Developing your Game` section in `README.md` is currently not working.

Thank you for your help!

**Comment by Motonstron** [comment]
Awesome, glad it worked for you! Please let me know if you have any other feedback about the generator.

I'll update the README.md as soon as possible, a few things have changed with the project ownership recently so I may have missed updating some links.

^_^
